name: cv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1=h57928b3_3
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=py39haa95532_0
  - aom=3.9.1=he0c23c2_0
  - astroid=3.3.9=py39hcbf5309_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli-python=1.0.9=py39h5da7b33_9
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.5=h2466b09_0
  - c-blosc2=2.15.2=h9e57077_1
  - ca-certificates=2025.4.26=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.2.1=py39h214f63a_1
  - cuda-cudart=12.8.90=he0c23c2_1
  - cuda-cudart_win-64=12.8.90=he0c23c2_1
  - cuda-cupti=12.8.90=he0c23c2_0
  - cuda-nvrtc=12.8.93=he0c23c2_0
  - cuda-version=12.8=h5d125a7_3
  - cudnn=9.8.0.87=h1361d0a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.11=py39h827c3e9_1
  - dav1d=1.2.1=hcfcfb64_0
  - dill=0.3.9=pyhd8ed1ab_1
  - ffmpeg=6.1.2=gpl_h63b3451_706
  - filelock=3.17.0=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py39h827c3e9_0
  - freetype=2.13.3=h0b5ce68_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - giflib=5.2.2=h64bf75a_0
  - glib=2.82.2=h3d4babf_1
  - glib-tools=2.82.2=h4394cf3_1
  - gmp=6.3.0=hfeafd45_2
  - graphite2=1.3.13=h63175ca_1003
  - grpcio=1.68.2=py39he5e857b_0
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - gudhi=3.11.0=py39h62f8235_4
  - harfbuzz=9.0.0=h2bedf89_1
  - huggingface_hub=0.29.2=py39haa95532_0
  - icu=75.1=he0c23c2_0
  - idna=3.7=py39haa95532_0
  - imagecodecs=2024.12.30=py39h2fc6b30_0
  - imageio=2.37.0=py39haa95532_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_resources=6.4.0=py39haa95532_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - isort=6.0.1=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=py39haa95532_0
  - jxrlib=1.1=he774522_2
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.21.3=hdf4eb48_0
  - lazy_loader=0.4=py39haa95532_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.3=hcdb6601_0
  - libavif16=1.1.1=h4d049a7_2
  - libblas=3.9.0=31_h641d27c_mkl
  - libboost=1.86.0=hb0986bb_3
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=19.1.7=default_ha5278ca_2
  - libcublas=12.8.4.1=he0c23c2_0
  - libcudss=0.5.0.16=hffc9a7f_1
  - libcufft=11.3.3.83=he0c23c2_0
  - libcurand=10.3.9.90=he0c23c2_0
  - libcusolver=11.7.3.90=he0c23c2_0
  - libcusparse=12.5.8.93=he0c23c2_0
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.23=h9062f6e_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.6=h537db12_0
  - libgcc=14.2.0=h1383e82_2
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_2
  - libgrpc=1.68.2=h0ac93cb_0
  - libheif=1.19.6=gpl_h2684147_100
  - libhwloc=2.11.2=default_ha69328c_1001
  - libhwy=1.2.0=h1d1702c_0
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libjxl=0.11.1=ha161b08_1
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblzma=5.6.4=h2466b09_0
  - liblzma-devel=5.6.4=h2466b09_0
  - libmagma=2.8.0=h630bcb8_2
  - libnvjitlink=12.8.93=he0c23c2_0
  - libnvjpeg=12.3.5.92=hcb8d914_0
  - libogg=1.3.5=h2bbff1b_1
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.47=had7236b_0
  - libprotobuf=5.28.3=h8309712_1
  - libre2-11=2024.07.02=h4eb7d71_2
  - libsqlite=3.49.1=h67fdade_2
  - libtiff=4.7.0=h797046b_3
  - libtorch=2.5.1=cuda126_mkl_hd91aefa_315
  - libuv=1.50.0=h2466b09_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.6=he286e8c_0
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=ha925a31_0
  - lightning-utilities=0.11.9=py39haa95532_0
  - lz4-c=1.10.0=h2466b09_1
  - markdown=3.4.1=py39haa95532_0
  - markupsafe=3.0.2=py39hf73967f_1
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mkl=2024.2.2=h66d3029_15
  - mpfr=4.2.1=hbc20e70_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=2.0.2=py39h60232e0_1
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - packaging=24.2=py39haa95532_0
  - pandas=2.2.3=py39h2366fc2_2
  - pcre2=10.44=h3d7b363_2
  - pillow=11.1.0=py39h73ef694_0
  - pip=25.0=py39haa95532_0
  - piq=0.8.0=pyhd8ed1ab_1
  - pixman=0.44.2=had0cd8c_0
  - platformdirs=4.3.7=pyh29332c3_0
  - ply=3.11=py39haa95532_0
  - protobuf=5.28.3=py39ha51f57c_0
  - pthread-stubs=0.4=h0e40799_1002
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyhab904b8_2
  - pycocotools=2.0.8=py39h4b0a98a_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pylint=3.3.5=pyh29332c3_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.5.1=cuda126_mkl_py39_h8fb42cc_315
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.6.0=py39h4b0a98a_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - qt-main=5.15.15=h9151539_2
  - rav1e=0.6.6=h975169c_2
  - re2=2024.07.02=haf4117d_2
  - requests=2.32.3=py39haa95532_1
  - safetensors=0.5.3=py39haa69e8e_0
  - scikit-image=0.24.0=py39h2366fc2_3
  - scikit-learn=1.6.1=py39h585ebfc_0
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=py39haa95532_2
  - setuptools=75.8.0=py39haa95532_0
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h7e360cc_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.45.3=h2bbff1b_0
  - svt-av1=2.3.0=he0c23c2_0
  - sympy=1.13.3=pyh04b8f61_5
  - tbb=2021.13.0=h62715c5_1
  - tensorboard=2.19.0=py39haa95532_0
  - tensorboard-data-server=0.7.0=py39haa95532_1
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - timm=1.0.15=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=py39haa95532_0
  - tomlkit=0.13.2=pyha770c72_1
  - torch-ema=0.3=pyhd8ed1ab_1
  - torchaudio=2.5.1=py39hc64d2fc_0
  - torchmetrics=1.2.1=py39haa95532_0
  - torchvision=0.20.1=cuda126_py39_h8cd1b8e_6
  - tornado=6.4.2=py39h827c3e9_0
  - tqdm=4.67.1=py39h9909e9c_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py39h827c3e9_1
  - urllib3=2.3.0=py39haa95532_0
  - vc=14.42=haa95532_4
  - vc14_runtime=14.42.34438=hfd919c2_24
  - vs2015_runtime=14.42.34438=h7142326_24
  - werkzeug=3.1.3=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h208afaa_0
  - xz-tools=5.6.4=h2466b09_0
  - yaml=0.2.5=he774522_0
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.21.0=py39haa95532_0
  - zlib-ng=2.2.4=hbb528cf_0
  - zstd=1.5.7=hbeecb71_1
  - pip:
      - albucore==0.0.23
      - albumentations==2.0.5
      - annotated-types==0.7.0
      - eval-type-backport==0.2.2
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - simsimd==6.2.1
      - stringzilla==3.12.3
      - typing-inspection==0.4.0
prefix: C:\Users\user\anaconda3\envs\cv
